name: Build new theme and push to `build-blocks` branch.

on:
    push:
        branches:
            - trunk
        paths:
            - public_html/wp-content/themes/wporg-pattern-directory-2024/**
    # Enable manually running action if necessary.
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

            - name: Setup
              uses: WordPress/wporg-repo-tools/.github/actions/setup@trunk
              with:
                token: ${{ secrets.GITHUB_TOKEN }}

            - name: Remove build artifacts
              run: |
                  rm -rf public_html/wp-content/themes/wporg-pattern-directory-2024/node_modules

            - name: Ignore .gitignore
              run: |
                  git add public_html/wp-content/themes/wporg-pattern-directory-2024/* --force

            - name: Append build number to version
              run: |
                current_version=$(grep -oP 'Version: \K[0-9]+\.[0-9]+\.[0-9]+' public_html/wp-content/themes/wporg-pattern-directory-2024/style.css)
                new_version="${current_version}-${GITHUB_SHA::7}"
                sed -i "s/Version: $current_version/Version: $new_version/" public_html/wp-content/themes/wporg-pattern-directory-2024/style.css
                
            - name: Commit and push
              # Using a specific hash here instead of a tagged version, for risk mitigation, since this action modifies our repo.
              uses: actions-js/push@a52398fac807b0c1e5f1492c969b477c8560a0ba # 1.3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  branch: build-blocks
                  force: true
                  message: 'Build: ${{ github.sha }}'
