name: Static Analysis (Linting)

# This workflow is triggered on pushes to trunk, and any PRs.
on:
    push:
        branches: [trunk]
    pull_request:
    # Enable manually running action if necessary.
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
    cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
    php:
        name: PHP

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Install Composer dependencies
              uses: ramsey/composer-install@65e4f84970763564f46a70b8a54b90d033b3bdda # v4.0.0

            - name: Lint PHP
              run: composer run lint

    js-css:
        name: JS & CSS

        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

            - name: Setup Node dependencies
              uses: ./.github/actions/setup-node-deps

            - name: Lint CSS
              run: npm run lint:css --workspaces --if-present

            - name: Lint JS
              run: npm run lint:js --workspaces --if-present
